### ISSUE TITLE
Searching for movies take a while

### ISSUE THREAD

**Issue by scp777** [Monash-FIT3170/The-Watchlist#115]
When searching for a movie, the loading seems to be looping through a selection and constantly refreshing, rather than showing straight away what I am trying to find.

Searching for a movie seems to loop through potential movies that match the search query. This looping appears on the front end. Perhaps a better search algorithm, adding a loading screen or PAAS issues.

**Comment by lachlandurra** [comment]
should be fixed but will have to test on deployment branch once pull request is approved
