### ISSUE TITLE
long list name makes menu very big

### ISSUE THREAD

**Issue by NikkiShao** [Monash-FIT3170/The-Watchlist#117]
adding a long list name makes menu very large on the left side and popup also very large
![image](https://github.com/user-attachments/assets/55e7779f-5e9d-4f38-8e21-c68451e72c2d)
![image](https://github.com/user-attachments/assets/e177f2fe-e2cf-4b6a-b525-95ffa6cc3a02)

**Comment by lachlandurra** [comment]
working on this
