### ISSUE TITLE
Special characters in search query breaks the app

### ISSUE THREAD

**Issue by joshualoongwy** [Monash-FIT3170/The-Watchlist#120]
Recreate:
- Go to search, in the search bar, enter a special character, e.g. ?, *, #.
- App breaks (with a regex error in console)

**Comment by lachlandurra** [comment]
fixed as a side effect of fixing #115

**Comment by lachlandurra** [comment]
> fixed as a side effect of fixing #115

not actually fixed, still some characters that break it. Now fixed with #144
