### ISSUE TITLE
Plus icon css

### ISSUE THREAD

**Issue by RyanAHicks** [Monash-FIT3170/The-Watchlist#123]
Plus icon when adding movies or shows... is like a pixel below centre

**Comment by lachlandurra** [comment]
fixed :)

**Comment by RyanAHicks** [comment]
I’m so proud of you, really resolves my ocd hahaOn 17 Sep 2024, at 7:49 PM, lachlandurra ***@***.***> wrote:﻿
Closed #123 as completed.
