### ISSUE TITLE
Searching lists

### ISSUE THREAD

**Issue by CameronNguyen0** [Monash-FIT3170/The-Watchlist#129]
Cannot search other user's lists

**Comment by lachlandurra** [comment]
I think we should make it so that the user can search for any **visible/non-private** list. Believe @m-ramm is working on list visibility.

**Comment by m-ramm** [comment]
Thanks for the mention @lachlandurra. This is a ticketed clickup item already, so will pick this issue up. Cheers

**Comment by lachlandurra** [comment]
this is basically done, can now search other users' lists, will be modified to only be able to search visible lists once that component is finalised.

**Comment by m-ramm** [comment]
Visibility feature implemented PR#171, closing issue
