### ISSUE TITLE
Inconsistent ProfileDropdown placement 

### ISSUE THREAD

**Issue by FourPawnsAttack** [Monash-FIT3170/The-Watchlist#182]
The ProfileDropdown moves slightly in the homepage compared to other pages
![image](https://github.com/user-attachments/assets/256931fe-aa31-4bff-9c9b-777708cec608)
![image](https://github.com/user-attachments/assets/d4e925f7-ae01-4bf4-9733-962ea4f6cdef)

**Comment by BrianNge341** [comment]
I'll fix this

**Comment by BrianNge341** [comment]
This is fixed
