### ISSUE TITLE
AI Picks last content gets cut off

### ISSUE THREAD

**Issue by Geomher** [Monash-FIT3170/The-Watchlist#221]
![image](https://github.com/user-attachments/assets/1e95e611-53df-4faa-a7e0-62ca1f560f54)

**Comment by chrish0w** [comment]
Thanks for pointing out the issue Geo, I will make sure to fix this to ensure that the last movie in the list for AI Picks page is displayed properly

**Comment by chrish0w** [comment]
This issue has been fixed now
