### ISSUE TITLE
Global Ratings don't show on some pages

### ISSUE THREAD

**Issue by Geomher** [Monash-FIT3170/The-Watchlist#223]
Global ratings do not appear on AI Picks page and Shared Watchlist page. On the shared watchlist page, the ratings of the user who owns the list should be displayed instead of global (unless they haven't rated a content)
![image](https://github.com/user-attachments/assets/9868d1b1-e804-447c-9aa0-ebda0c48472b)

**Comment by lachlandurra** [comment]
not sure what branch this is but global ratings appear on AI picks page. Will implement on shared watchlist page (remember to pass global ratings through to new components...)
